-- Controle de Expedições e Rastreio - Supabase V4
-- Execute este arquivo no SQL Editor do seu projeto Supabase.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null,
    email text not null,
    full_name text not null default '',
    role text not null default 'viewer' check (role in ('admin', 'operator', 'viewer')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    last_login timestamptz
);

create unique index if not exists profiles_username_lower_uidx on public.profiles (lower(username));
create unique index if not exists profiles_email_lower_uidx on public.profiles (lower(email));

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    order_number text not null unique,
    expedition_start date not null,
    created_at timestamptz not null default now(),
    created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.invoices (
    nf_number text primary key,
    order_id bigint references public.orders(id) on delete set null,
    first_seen_at timestamptz not null default now()
);

create table if not exists public.tracking_current (
    nf_number text primary key references public.invoices(nf_number) on delete cascade,
    data_frete text,
    tipo_frete text,
    minuta text,
    cte text,
    serie text,
    emissao_cte text,
    destinatario text,
    cidade_destinatario text,
    uf_destinatario text,
    volumes text,
    peso_real text,
    valor_nf text,
    total_frete text,
    prazo_entrega text,
    ultima_ocorrencia text,
    data_ultima_ocorrencia text,
    occurrence_ts timestamptz,
    source_filename text,
    updated_at timestamptz not null default now()
);

create table if not exists public.tracking_history (
    row_hash text primary key,
    nf_number text not null references public.invoices(nf_number) on delete cascade,
    data_frete text,
    tipo_frete text,
    minuta text,
    cte text,
    serie text,
    emissao_cte text,
    destinatario text,
    cidade_destinatario text,
    uf_destinatario text,
    volumes text,
    peso_real text,
    valor_nf text,
    total_frete text,
    prazo_entrega text,
    ultima_ocorrencia text,
    data_ultima_ocorrencia text,
    occurrence_ts timestamptz,
    source_filename text,
    imported_at timestamptz not null default now()
);

create index if not exists tracking_history_nf_idx on public.tracking_history(nf_number);
create index if not exists tracking_history_occurrence_idx on public.tracking_history(occurrence_ts desc);

create table if not exists public.imports (
    id bigint generated by default as identity primary key,
    filename text not null,
    imported_at timestamptz not null default now(),
    rows_read integer not null,
    nf_mentions integer not null,
    new_history_records integer not null,
    imported_by uuid references auth.users(id) on delete set null
);

create table if not exists public.audit_log (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    username text,
    action text not null,
    details text,
    created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx on public.audit_log(created_at desc);

-- Cria automaticamente um perfil básico quando um usuário nasce no Supabase Auth.
-- O perfil começa como viewer por segurança; administradores são promovidos via service role.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, username, email, full_name, role, is_active)
    values (
        new.id,
        coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(coalesce(new.email, new.id::text), '@', 1)),
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        'viewer',
        true
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- Funções auxiliares para RLS.
create or replace function public.is_active_app_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.is_active = true
    );
$$;

create or replace function public.has_app_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.is_active = true
          and p.role = any(allowed_roles)
    );
$$;

-- RLS
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.invoices enable row level security;
alter table public.tracking_current enable row level security;
alter table public.tracking_history enable row level security;
alter table public.imports enable row level security;
alter table public.audit_log enable row level security;

-- Remove políticas antigas se o script for reexecutado.
drop policy if exists profiles_select_policy on public.profiles;
drop policy if exists orders_select_policy on public.orders;
drop policy if exists orders_insert_policy on public.orders;
drop policy if exists orders_update_policy on public.orders;
drop policy if exists orders_delete_policy on public.orders;
drop policy if exists invoices_select_policy on public.invoices;
drop policy if exists invoices_insert_policy on public.invoices;
drop policy if exists invoices_update_policy on public.invoices;
drop policy if exists invoices_delete_policy on public.invoices;
drop policy if exists tracking_current_select_policy on public.tracking_current;
drop policy if exists tracking_current_insert_policy on public.tracking_current;
drop policy if exists tracking_current_update_policy on public.tracking_current;
drop policy if exists tracking_current_delete_policy on public.tracking_current;
drop policy if exists tracking_history_select_policy on public.tracking_history;
drop policy if exists tracking_history_insert_policy on public.tracking_history;
drop policy if exists tracking_history_update_policy on public.tracking_history;
drop policy if exists tracking_history_delete_policy on public.tracking_history;
drop policy if exists imports_select_policy on public.imports;
drop policy if exists imports_insert_policy on public.imports;
drop policy if exists audit_insert_policy on public.audit_log;
drop policy if exists audit_select_policy on public.audit_log;

create policy profiles_select_policy
on public.profiles for select
to authenticated
using (id = auth.uid() or public.has_app_role(array['admin']));

create policy orders_select_policy
on public.orders for select to authenticated
using (public.is_active_app_user());
create policy orders_insert_policy
on public.orders for insert to authenticated
with check (public.has_app_role(array['admin','operator']));
create policy orders_update_policy
on public.orders for update to authenticated
using (public.has_app_role(array['admin','operator']))
with check (public.has_app_role(array['admin','operator']));
create policy orders_delete_policy
on public.orders for delete to authenticated
using (public.has_app_role(array['admin']));

create policy invoices_select_policy
on public.invoices for select to authenticated
using (public.is_active_app_user());
create policy invoices_insert_policy
on public.invoices for insert to authenticated
with check (public.has_app_role(array['admin','operator']));
create policy invoices_update_policy
on public.invoices for update to authenticated
using (public.has_app_role(array['admin','operator']))
with check (public.has_app_role(array['admin','operator']));
create policy invoices_delete_policy
on public.invoices for delete to authenticated
using (public.has_app_role(array['admin']));

create policy tracking_current_select_policy
on public.tracking_current for select to authenticated
using (public.is_active_app_user());
create policy tracking_current_insert_policy
on public.tracking_current for insert to authenticated
with check (public.has_app_role(array['admin','operator']));
create policy tracking_current_update_policy
on public.tracking_current for update to authenticated
using (public.has_app_role(array['admin','operator']))
with check (public.has_app_role(array['admin','operator']));
create policy tracking_current_delete_policy
on public.tracking_current for delete to authenticated
using (public.has_app_role(array['admin']));

create policy tracking_history_select_policy
on public.tracking_history for select to authenticated
using (public.is_active_app_user());
create policy tracking_history_insert_policy
on public.tracking_history for insert to authenticated
with check (public.has_app_role(array['admin','operator']));
create policy tracking_history_update_policy
on public.tracking_history for update to authenticated
using (public.has_app_role(array['admin','operator']))
with check (public.has_app_role(array['admin','operator']));
create policy tracking_history_delete_policy
on public.tracking_history for delete to authenticated
using (public.has_app_role(array['admin']));

create policy imports_select_policy
on public.imports for select to authenticated
using (public.is_active_app_user());
create policy imports_insert_policy
on public.imports for insert to authenticated
with check (public.has_app_role(array['admin','operator']));

create policy audit_insert_policy
on public.audit_log for insert to authenticated
with check (public.is_active_app_user() and user_id = auth.uid());
create policy audit_select_policy
on public.audit_log for select to authenticated
using (public.has_app_role(array['admin']));

-- Permissões da Data API. RLS continua sendo a barreira de acesso.
grant usage on schema public to authenticated, service_role;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.orders to authenticated;
grant select, insert, update, delete on public.invoices to authenticated;
grant select, insert, update, delete on public.tracking_current to authenticated;
grant select, insert, update, delete on public.tracking_history to authenticated;
grant select, insert on public.imports to authenticated;
grant select, insert on public.audit_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant execute on function public.is_active_app_user() to authenticated, service_role;
grant execute on function public.has_app_role(text[]) to authenticated, service_role;
